<?php

namespace Database\Seeders;

use App\Models\Employee;
use Illuminate\Database\Seeder;

class EmployeeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $data = [
            [
                "employee_code" => "EMP0000",
                "employee_name" => "SUPER USER",
                "nik" => 0,
                "department_code" => "DEPT002",
                "section_code" => "SECT004",
                "birth_date" => "1899-08-10",
                "birth_place" => "Surabaya",
                "phone_number" => 0,
                "phone_number_2" => 0,
                "email" => "superuser@gmail.com",
                "gender" => "Laki - laki",
                "grade_title_code" => "GDT001",
                "religion" => "Islam",
                "start_date" => "1899-12-13",
                "end_date" =>  "1899-12-13",
                "address" => "Mojokerto",
                "address_2" => "Kab. Mojokerto",
                "direct_leader_code" => "EMP0000",
                "status_job" => "Tetap",
                "marital_status_code" => "MRTL002",
                "bank_code" => "BANK001",
                "rekening_number" => 0
            ],
            [
                "employee_code" => "EMP0001",
                "employee_name" => "NURDIAN PURWARINI",
                "nik" => '3507134109770000',
                "department_code" => "DEPT002",
                "section_code" => "SECT003",
                "birth_date" => "1977-09-01",
                "birth_place" => "Sidoarjo",
                "phone_number" => '85851506454',
                "phone_number_2" => 0,
                "email" => "nurdianpurwarini@gmail.com",
                "gender" => "Perempuan",
                "grade_title_code" => "GDT003",
                "religion" => "Islam",
                "start_date" => "1899-12-13",
                "end_date" =>  "1899-12-13",
                "address" => "JL. SUMBER NO.17. RT 03-RW 04. PANGGUNGREJO. KEPANJEN. MALANG",
                "address_2" => "Malang",
                "direct_leader_code" => "EMP0000",
                "status_job" => "Tetap",
                "marital_status_code" => "MRTL001",
                "bank_code" => "BANK024",
                "rekening_number" => '1440020553183'
            ],
            [
                "employee_code" => "EMP0002",
                "employee_name" => "SULISTYOWATI",
                "nik" => '3507244404750000',
                "department_code" => "DEPT003",
                "section_code" => "SECT007",
                "birth_date" => "1975-04-04",
                "birth_place" => "Malang",
                "phone_number" => '81333378442',
                "phone_number_2" => 0,
                "email" => "sulistyowati@gmail.com",
                "gender" => "Perempuan",
                "grade_title_code" => "GDT004",
                "religion" => "Islam",
                "start_date" => "1899-12-13",
                "end_date" =>  "1899-12-13",
                "address" => "JL. ROGONOTO. GG MERDEKA 13. RT 03-RW 04. LOSARI. SINGOSARI. MALANG",
                "address_2" => "Malang",
                "direct_leader_code" => "EMP0000",
                "status_job" => "Kontrak",
                "marital_status_code" => "MRTL002",
                "bank_code" => "BANK024",
                "rekening_number" => '1440020553217'
            ],
            [
                "employee_code" => "EMP0003",
                "employee_name" => "JUJU JUMHANA",
                "nik" => '3514111307620000',
                "department_code" => "DEPT004",
                "section_code" => "SECT008",
                "birth_date" => "1962-07-13",
                "birth_place" => "Pandeglang",
                "phone_number" => '817374123',
                "phone_number_2" => 0,
                "email" => "jujujumhana@gmail.com",
                "gender" => "Laki - laki",
                "grade_title_code" => "GDT002",
                "religion" => "Islam",
                "start_date" => "1899-12-13",
                "end_date" =>  "1899-12-13",
                "address" => "KUTOREJO INDAH BLOK B NO.04. RT 03- RW 01. PANDAAN. PASURUAN",
                "address_2" => "Pasuruan",
                "direct_leader_code" => "EMP0000",
                "status_job" => "Tetap",
                "marital_status_code" => "MRTL002",
                "bank_code" => "BANK024",
                "rekening_number" => '1440020553159'
            ],
            [
                "employee_code" => "EMP0004",
                "employee_name" => "AMIR NISWAN",
                "nik" => '3514121206810010',
                "department_code" => "DEPT005",
                "section_code" => "SECT011",
                "birth_date" => "1981-06-12",
                "birth_place" => "Mataram",
                "phone_number" => '83833001373',
                "phone_number_2" => 0,
                "email" => "amirniswan@gmail.com",
                "gender" => "Laki - laki",
                "grade_title_code" => "GDT004",
                "religion" => "Islam",
                "start_date" => "1899-12-13",
                "end_date" =>  "1899-12-13",
                "address" => "KISIK. RT 04- RW 11. GEMPOL. PASURUAN",
                "address_2" => "Pasuruan",
                "direct_leader_code" => "EMP0000",
                "status_job" => "Kontrak",
                "marital_status_code" => "MRTL002",
                "bank_code" => "BANK024",
                "rekening_number" => '1440020553233'
            ],
            [
                "employee_code" => "EMP0005",
                "employee_name" => "FISTA RACHMA DANIANTA",
                "nik" => '3576012804900000',
                "department_code" => "DEPT006",
                "section_code" => "SECT012",
                "birth_date" => "1990-04-28",
                "birth_place" => "Mojokerto",
                "phone_number" => '82234609578',
                "phone_number_2" => 0,
                "email" => "fistarachmadanianta@gmail.com",
                "gender" => "Laki - laki",
                "grade_title_code" => "GDT004",
                "religion" => "Islam",
                "start_date" => "1899-12-13",
                "end_date" =>  "1899-12-13",
                "address" => "SURODINAWAN. RT 04- RW 01. PRAJURITKULON. KOTA MOJOKERTO",
                "address_2" => "Kota Mojokerto",
                "direct_leader_code" => "EMP0000",
                "status_job" => "Kontrak",
                "marital_status_code" => "MRTL001",
                "bank_code" => "BANK024",
                "rekening_number" => '1440020553225'
            ],
            [
                "employee_code" => "EMP0006",
                "employee_name" => "MANSYUR",
                "nik" => '3514111202670000',
                "department_code" => "DEPT001",
                "section_code" => "SECT002",
                "birth_date" => "1967-02-12",
                "birth_place" => "Pasuruan",
                "phone_number" => '85233449513',
                "phone_number_2" => 0,
                "email" => "mansyur@gmail.com",
                "gender" => "Laki - laki",
                "grade_title_code" => "GDT006",
                "religion" => "Islam",
                "start_date" => "1899-12-13",
                "end_date" =>  "1899-12-13",
                "address" => "DUSUN BEGAGAH. RT 03- RW 01. KEMIRISEWU. PANDAAN. PASURUAN",
                "address_2" => "Pasuruan",
                "direct_leader_code" => "EMP0013",
                "status_job" => "Kontrak",
                "marital_status_code" => "MRTL001",
                "bank_code" => "BANK024",
                "rekening_number" => '1440020553597'
            ],
            [
                "employee_code" => "EMP0007",
                "employee_name" => "TOSIN",
                "nik" => '3514112505750000',
                "department_code" => "DEPT001",
                "section_code" => "SECT001",
                "birth_date" => "1975-05-25",
                "birth_place" => "Pasuruan",
                "phone_number" => '85806624402',
                "phone_number_2" => 0,
                "email" => "tosin@gmail.com",
                "gender" => "Laki - laki",
                "grade_title_code" => "GDT006",
                "religion" => "Islam",
                "start_date" => "12-01-2015",
                "end_date" => "06-30-2024",
                "address" => "DUSUN CLUMPRIT. RT 01- RW 11. SEBANI. PANDAAN",
                "address_2" => "Pasuruan",
                "direct_leader_code" => "EMP0013",
                "status_job" => "Kontrak",
                "marital_status_code" => "MRTL002",
                "bank_code" => "BANK024",
                "rekening_number" => '1440020553605'
            ],
            [
                "employee_code" => "EMP0008",
                "employee_name" => "KUSAERI",
                "nik" => '3514112106830000',
                "department_code" => "DEPT001",
                "section_code" => "SECT001",
                "birth_date" => "1983-06-21",
                "birth_place" => "Pasuruan",
                "phone_number" => '81554672622',
                "phone_number_2" => 0,
                "email" => "kusaeri@gmail.com",
                "gender" => "Laki - laki",
                "grade_title_code" => "GDT006",
                "religion" => "Islam",
                "start_date" => "1899-12-13",
                "end_date" =>  "1899-12-13",
                "address" => "DUSUN CLUMPRIT RT 06- RW 13. SEBANI. PANDAAN",
                "address_2" => "Pasuruan",
                "direct_leader_code" => "EMP0013",
                "status_job" => "Kontrak",
                "marital_status_code" => "MRTL001",
                "bank_code" => "BANK024",
                "rekening_number" => '1440020553589'
            ],
            [
                "employee_code" => "EMP0009",
                "employee_name" => "MAMAN RUSDI ARTO",
                "nik" => '3515132708910000',
                "department_code" => "DEPT006",
                "section_code" => "SECT012",
                "birth_date" => "1991-08-21",
                "birth_place" => "Sidoarjo",
                "phone_number" => '8782936188',
                "phone_number_2" => 0,
                "email" => "mamanrusdiarto@gmail.com",
                "gender" => "Laki - laki",
                "grade_title_code" => "GDT006",
                "religion" => "Islam",
                "start_date" => "1899-12-13",
                "end_date" =>  "1899-12-13",
                "address" => "SIDOROGO. RT 01-RW 05. TROSOBO. TAMAN. SIDOARJO",
                "address_2" => "Sidoarjo",
                "direct_leader_code" => "EMP0013",
                "status_job" => "Kontrak",
                "marital_status_code" => "MRTL001",
                "bank_code" => "BANK024",
                "rekening_number" => '1440020553357'
            ],
            [
                "employee_code" => "EMP0010",
                "employee_name" => "MOHAMMAD ROMADHON",
                "nik" => '3515130904900000',
                "department_code" => "DEPT006",
                "section_code" => "SECT012",
                "birth_date" => "1990-04-09",
                "birth_place" => "Sidoarjo",
                "phone_number" => '83832688883',
                "phone_number_2" => 0,
                "email" => "mohammadromadhon@gmail.com",
                "gender" => "Laki - laki",
                "grade_title_code" => "GDT006",
                "religion" => "Islam",
                "start_date" => "1899-12-13",
                "end_date" =>  "1899-12-13",
                "address" => "TAWANGSARI. RT 11. RW 02. TAMAN. SIDOARJO",
                "address_2" => "Sidoarjo",
                "direct_leader_code" => "EMP0013",
                "status_job" => "Kontrak",
                "marital_status_code" => "MRTL002",
                "bank_code" => "BANK024",
                "rekening_number" => '1440020553340'
            ],
            [
                "employee_code" => "EMP0011",
                "employee_name" => "RIA AYU WARDANI",
                "nik" => '3509176202930000',
                "department_code" => "DEPT004",
                "section_code" => "SECT008",
                "birth_date" => "1993-02-22",
                "birth_place" => "Jember",
                "phone_number" => '81216490610',
                "phone_number_2" => 0,
                "email" => "riaayuwardani@gmail.com",
                "gender" => "Perempuan",
                "grade_title_code" => "GDT004",
                "religion" => "Kristen",
                "start_date" => "05-02-2018",
                "end_date" => "12-31-1899",
                "address" => "DUSUN GUMUK SEGAWE. RT 01-RW 01. PANCAKARYA. AJUNG. JEMBER",
                "address_2" => "Jember",
                "direct_leader_code" => "EMP0003",
                "status_job" => "Tetap",
                "marital_status_code" => "MRTL001",
                "bank_code" => "BANK024",
                "rekening_number" => '1440020553175'
            ],
            [
                "employee_code" => "EMP0012",
                "employee_name" => "SYUKMA RARA YOULANDA",
                "nik" => '3514115808920000',
                "department_code" => "DEPT005",
                "section_code" => "SECT010",
                "birth_date" => "1992-08-18",
                "birth_place" => "Pasuruan",
                "phone_number" => '85735056882',
                "phone_number_2" => 0,
                "email" => "syukmararayoulanda@gmail.com",
                "gender" => "Perempuan",
                "grade_title_code" => "GDT005",
                "religion" => "Islam",
                "start_date" => "1899-12-13",
                "end_date" =>  "1899-12-13",
                "address" => "DUSUN KLANGKUNG. RT 06-RW 09. NOGOSARI. PANDAAN. PASURUAN",
                "address_2" => "Pasuruan",
                "direct_leader_code" => "EMP0004",
                "status_job" => "Tetap",
                "marital_status_code" => "MRTL001",
                "bank_code" => "BANK024",
                "rekening_number" => '1440020553241'
            ],
            [
                "employee_code" => "EMP0013",
                "employee_name" => "DEKRI LUTFIANTO",
                "nik" => '3514141008820000',
                "department_code" => "DEPT004",
                "section_code" => "SECT009",
                "birth_date" => "1982-08-10",
                "birth_place" => "Pasuruan",
                "phone_number" => '82244601850',
                "phone_number_2" => 0,
                "email" => "dekrilutfianto@gmail.com",
                "gender" => "Laki - laki",
                "grade_title_code" => "GDT004",
                "religion" => "Islam",
                "start_date" => "1899-12-13",
                "end_date" =>  "1899-12-13",
                "address" => "PERUM TAMAN PERMATA INDAHBLOK C6-2 RT 03-RW04. PAGAK. BEJI. PASURUAN",
                "address_2" => "Pasuruan",
                "direct_leader_code" => "EMP0003",
                "status_job" => "Kontrak",
                "marital_status_code" => "MRTL003",
                "bank_code" => "BANK024",
                "rekening_number" => '1440020553167'
            ],
            [
                "employee_code" => "EMP0014",
                "employee_name" => "ALI ZAINAL ABIDIN",
                "nik" => '3525160405900000',
                "department_code" => "DEPT002",
                "section_code" => "SECT004",
                "birth_date" => "1990-05-04",
                "birth_place" => "Pasuruan",
                "phone_number" => '81327455276',
                "phone_number_2" => 0,
                "email" => "alizainalabidin@gmail.com",
                "gender" => "Laki - laki",
                "grade_title_code" => "GDT005",
                "religion" => "Islam",
                "start_date" => "1899-12-13",
                "end_date" =>  "1899-12-13",
                "address" => "JL. MALIK IBRAHIM 51. RT 02- RW 02. GAPUROSUKOLILO. GRESIK.",
                "address_2" => "Gresik",
                "direct_leader_code" => "EMP0001",
                "status_job" => "Kontrak",
                "marital_status_code" => "MRTL003",
                "bank_code" => "BANK024",
                "rekening_number" => '1440020553191'
            ],
            [
                "employee_code" => "EMP0015",
                "employee_name" => "ILHAM RIZKI SAPUTRO",
                "nik" => '3578083103950000',
                "department_code" => "DEPT005",
                "section_code" => "SECT010",
                "birth_date" => "1995-03-31",
                "birth_place" => "Kediri",
                "phone_number" => "08333244240",
                "phone_number_2" => 0,
                "email" => "ilhamrizkisaputro@gmail.com",
                "gender" => "Laki - laki",
                "grade_title_code" => "GDT006",
                "religion" => "Islam",
                "start_date" => "1899-12-13",
                "end_date" =>  "1899-12-13",
                "address" => "JL. KEDUNG TARUKAN BATU I-14A. RT 01- RW 06. MOJO. GUBENG. SURABAYA",
                "address_2" => "Surabaya",
                "direct_leader_code" => "EMP0004",
                "status_job" => "Kontrak",
                "marital_status_code" => "MRTL003",
                "bank_code" => "BANK024",
                "rekening_number" => '1440020553449'
            ],
            [
                "employee_code" => "EMP0016",
                "employee_name" => "REGO ARISTA WIBOWO",
                "nik" => '3514112406880000',
                "department_code" => "DEPT005",
                "section_code" => "SECT010",
                "birth_date" => "1988-06-24",
                "birth_place" => "Pasuruan",
                "phone_number" => '85649537171',
                "phone_number_2" => 0,
                "email" => "regoaristawibowo@gmail.com",
                "gender" => "Laki - laki",
                "grade_title_code" => "GDT006",
                "religion" => "Budha",
                "start_date" => "1899-12-13",
                "end_date" =>  "1899-12-13",
                "address" => "DUSUN NAMPES. RT 07- RW 04. NOGOSARI. PANDAAN. PASURUAN",
                "address_2" => "Pasuruan",
                "direct_leader_code" => "EMP0004",
                "status_job" => "Kontrak",
                "marital_status_code" => "MRTL002",
                "bank_code" => "BANK024",
                "rekening_number" => '1440020553506'
            ],
            [
                "employee_code" => "EMP0017",
                "employee_name" => "ARIF SUMANTRI",
                "nik" => '3514121912970000',
                "department_code" => "DEPT005",
                "section_code" => "SECT010",
                "birth_date" => "1997-02-19",
                "birth_place" => "Pasuruan",
                "phone_number" => '083833006836',
                "phone_number_2" => 0,
                "email" => "arifsumantri@gmail.com",
                "gender" => "Laki - laki",
                "grade_title_code" => "GDT006",
                "religion" => "Islam",
                "start_date" => "1899-12-13",
                "end_date" =>  "1899-12-13",
                "address" => "DUSUN NGERONG. RT 05- RW 02. GEMPOL. PASURUAN",
                "address_2" => "Pasuruan",
                "direct_leader_code" => "EMP0004",
                "status_job" => "Kontrak",
                "marital_status_code" => "MRTL002",
                "bank_code" => "BANK024",
                "rekening_number" => '1440020582711'
            ],
            [
                "employee_code" => "EMP0018",
                "employee_name" => "ARDI ARIESTA SAPUTRA",
                "nik" => '3515162104910000',
                "department_code" => "DEPT006",
                "section_code" => "SECT013",
                "birth_date" => "1991-04-21",
                "birth_place" => "Trenggalek",
                "phone_number" => '083857259588',
                "phone_number_2" => 0,
                "email" => "ardiariestasaputra@gmail.com",
                "gender" => "Laki - laki",
                "grade_title_code" => "GDT006",
                "religion" => "Islam",
                "start_date" => "1899-12-13",
                "end_date" =>  "1899-12-13",
                "address" => "JL. KERTANEGARA 24 RT 05-RW 11 SAWOTRATAP. GEDANGAN. SIDOARJO",
                "address_2" => "Sidoarjo",
                "direct_leader_code" => "EMP0004",
                "status_job" => "Kontrak",
                "marital_status_code" => "MRTL002",
                "bank_code" => "BANK024",
                "rekening_number" => '1440020553308'
            ],
            [
                "employee_code" => "EMP0019",
                "employee_name" => "NURUL HIDAYATI",
                "nik" => '3514115904940000',
                "department_code" => "DEPT008",
                "section_code" => "SECT014",
                "birth_date" => "1994-04-19",
                "birth_place" => "Pasuruan",
                "phone_number" => '08564602104',
                "phone_number_2" => 0,
                "email" => "nurulhidayati@gmail.com",
                "gender" => "Perempuan",
                "grade_title_code" => "GDT005",
                "religion" => "Islam",
                "start_date" => "1899-12-13",
                "end_date" =>  "1899-12-13",
                "address" => "DUSUN NAMPES GG 1-5. RT 02- RW 01. NOGOSARI. PANDAAN",
                "address_2" => "Pasuruan",
                "direct_leader_code" => "EMP0004",
                "status_job" => "Kontrak",
                "marital_status_code" => "MRTL003",
                "bank_code" => "BANK024",
                "rekening_number" => '1440017301208'
            ]

        ];
        Employee::insert($data);
    }
}